### ISSUE TITLE
Dropping a table/view should make it disappear from the tables tab

### ISSUE THREAD

**Issue by twuebi** [lakekeeper/console#46]
Currently, we have to manually reload the tab to see the table disappear.

**Comment by v-kessler** [comment]
solved in https://github.com/lakekeeper/console/commit/edebbc735c2272d074451b1de0e944a1738e9e34

**Comment by twuebi** [comment]
Clicking on the garbage can next to a table doesn't make it disappear from the list, https://github.com/lakekeeper/console/commit/edebbc735c2272d074451b1de0e944a1738e9e34 enables me to click the tab to reload which is already an improvement but I feel it would be clearer if the item disappeared from the list after dropping it without needing manual refresh.

**Comment by v-kessler** [comment]
https://github.com/lakekeeper/console/pull/47
